version: "3.4"
services:
  photo-360-db-container:
    environment:
      - POSTGRES_USER=${DATABASE_LOGIN}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    container_name: ${DATABASE_CONTAINER_NAME}
    volumes:
      - photo-360-db-container:${VOLUME_LOCATION}
    ports:
      - ${DATABASE_EXTERNAL_PORT}:${DATABASE_INTERNAL_PORT}
    restart:
      always
    image: ${DATABASE_IMAGE}
    networks:
      - photo_360-network
    shm_size: 256m

  photo360-backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: photo360-backend-server
    depends_on:
      - photo-360-db-container
    networks:
      - photo_360-network

volumes:
  photo-360-db-container:

networks:
  photo_360-network: