name: Maven build and test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.yaml up -d

  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Build and test
        working-directory: ./photo360-backend
        run: mvn clean install