name: Maven build and test

on:
  pull_request:
    branches: '*'

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Containers
        run: docker-compose -f "docker-sys-photo360-conf/docker-compose.yaml" up -d --build

      - name: Wait for services to start
        run: sleep 10

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Build and test
        working-directory: ./
        run: mvn clean install

      - name: Stop and remove Docker Compose services
        if: always()
        run: docker-compose -f "docker-sys-photo360-conf/docker-compose.yaml" down
