name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          sudo docker-compose --version

      - name: Build and run Docker Compose services
        run: |
          docker-compose -f ../../docker-compose.yaml up -d

      - name: Wait for services to start (adjust the sleep duration)
        run: sleep 10

      - name: Run your tests (replace this with your actual testing command)
        run: |
          # Run your test commands here, e.g., for running tests against the created test database.
          # Example: npm test

      - name: Stop and remove Docker Compose services
        run: docker-compose -f ../../docker-compose.yaml down